@extends("front/master")
    @section("page_level_plugins")
        @stop
    @section("page_level_style")
        @stop
    @section("content")
        @stop
    @section("page_level_plugins_js")
        @stop
    @section("page_level_js")
        @stop